### ISSUE TITLE
把sdk修改为dot net standard吧！

### ISSUE THREAD

**Issue by quxian** [aliyun/aliyun-tablestore-csharp-sdk#11]
我看到sdk里面用到的库都没平台依赖，完全可以把项目属性修改为 standard 标准，没有任何副作用，代码都不用改一行，当时好处是很多的，所有平台都可以使用了。

改一改吧，希望听到社区的声音！

**Comment by wanttobeamaster** [comment]
> 我看到sdk里面用到的库都没平台依赖，完全可以把项目属性修改为 standard 标准，没有任何副作用，代码都不用改一行，当时好处是很多的，所有平台都可以使用了。
> 
> 改一改吧，希望听到社区的声音！

目前最新版本支持.NET Standard2.0，同时兼容.NET Framework4.0。欢迎体验，并给我们提供反馈意见哦～
