### ISSUE TITLE
Size() method in class 'AggregationResults' seems wrong in the new version 6.0.0 

### ISSUE THREAD

**Issue by Sean-Fang** [aliyun/aliyun-tablestore-csharp-sdk#19]
Hi, 
Very exciting to see the new version 6.0.0. 
I assume that the class 'AggregationResults' has a wrong if-condition in method Size(). The class is under the namespace [Aliyun.OTS.DataModel.Search.Agg].
Currently, the codes like,
````
public int Size()
{
    if (ResultMap != null)
    {
        return 0;
    }
    return ResultMap.Count;
}
````
However, the method might be meant to return 0 if the ResultMap **is** null.
Could you please kindly check it?

Sean

**Comment by wanttobeamaster** [comment]
Thank you for your comment, we will check it carefully and fix it as soon as possible if there is a problem, thanks again.

**Comment by wanttobeamaster** [comment]
> Hi, Very exciting to see the new version 6.0.0. I assume that the class 'AggregationResults' has a wrong if-condition in method Size(). The class is under the namespace [Aliyun.OTS.DataModel.Search.Agg]. Currently, the codes like,
> 
> ```
> public int Size()
> {
>     if (ResultMap != null)
>     {
>         return 0;
>     }
>     return ResultMap.Count;
> }
> ```
> 
> However, the method might be meant to return 0 if the ResultMap **is** null. Could you please kindly check it?
> 
> Sean

hi, we have fix this issue in commit https://github.com/aliyun/aliyun-tablestore-csharp-sdk/commit/b756a0a1f974cec4aab339432b40be506b6c9d3d. thanks for you feedback again.

**Comment by wanttobeamaster** [comment]
> Hi, Very exciting to see the new version 6.0.0. I assume that the class 'AggregationResults' has a wrong if-condition in method Size(). The class is under the namespace [Aliyun.OTS.DataModel.Search.Agg]. Currently, the codes like,
> 
> ```
> public int Size()
> {
>     if (ResultMap != null)
>     {
>         return 0;
>     }
>     return ResultMap.Count;
> }
> ```
> 
> However, the method might be meant to return 0 if the ResultMap **is** null. Could you please kindly check it?
> 
> Sean

hi, we have fixed this issue in commit https://github.com/aliyun/aliyun-tablestore-csharp-sdk/commit/b756a0a1f974cec4aab339432b40be506b6c9d3d. Thanks for your feedback again.
