### ISSUE TITLE
Error: invalid parameter when creating Search Index with Nested Field Type

### ISSUE THREAD

**Issue by Sean-Fang** [aliyun/aliyun-tablestore-csharp-sdk#20]
Hi,

Recently I got an error without any detailed information as below when I used .NET SDK to create a search index.

`Aliyun.OTS.OTSServerException: 'OTS request failed, API: /CreateSearchIndex, HTTPStatus: 400 BadRequest, ErrorCode: OTSParameterInvalid, ErrorMessage: invalid parameter, Request ID: 0005e889-e227-0ac8-69ab-c60b14c447aa'
`

I could create it successfully without involving NESTED Field Type.
The settings for NEST Field in FieldSchema is 
![1663052646722_7F2FC06A-2D09-46ac-B8D7-F7335D58F00E](https://user-images.githubusercontent.com/32961210/189838086-2df1eeee-5517-4730-a1c4-936fb26d7042.png)
AND the settings for request is 
![1663053064009_84C04C0D-02CA-49ab-A0C2-3E0B916765E7](https://user-images.githubusercontent.com/32961210/189838181-793ead89-a9be-4b2b-b5fd-64ebb82f4f55.png)
I already tried to modify the settings according to Aliyun TableStore docs but still failed. Like, change EnableSortAndAgg to false, index to false for NESTED field.

Could you please help to check if it was caused by my wrong settings? Or it is the SDK issue?
@wanttobeamaster 

Best regards,
Sean

**Comment by wanttobeamaster** [comment]
ok, I will check it and reply to you as soon as possible @Sean-Fang

**Comment by wanttobeamaster** [comment]
Hi, I have checked the problem you encountered, the reason is that the nested type does not need to set the IndexOptions, but the value is "DOCS" in default, so the creation of the index failed. we will fix this case as soon as possible. @Sean-Fang

**Comment by Sean-Fang** [comment]
> Hi, I have checked the problem you encountered, the reason is that the nested type does not need to set the IndexOptions, but the value is "DOCS" in default, so the creation of the index failed. we will fix this case as soon as possible. @Sean-Fang

I also suspected it after a few tries. Looking forward to receiving updates~

**Comment by wanttobeamaster** [comment]
> 

Hi, We have updated the sdk, and set the indexoptions as null in default when create search index. thanks for you feedback.
