### ISSUE TITLE
关于HttpClient的问题

### ISSUE THREAD

**Issue by zhouzf05** [aliyun/aliyun-tablestore-csharp-sdk#4]
OTS的C#SDK中，用了一个HttpClient的连接池，这种用法似乎是有问题
C# 的HttpClient本身是有连接池的，还有就是当连接池的连接用满的时候就公引起程序等待
直接把HttpClient做一个单例  可能比较合适

**Comment by danielxiaoran** [comment]
新版本的sdk 已经解决了这个问题
