### ISSUE TITLE
什么时候支持 .net core ? 最近公司想把项目升级成 .net core 

### ISSUE THREAD

**Issue by KarlHuang0509** [aliyun/aliyun-tablestore-csharp-sdk#9]

**Comment by bosima** [comment]
我fork了一个，已经支持.net core，https://github.com/bosima/aliyun-tablestore-csharp-sdk

**Comment by ghd258** [comment]
我们用都用net core 了 希望能官方支持

**Comment by o1298098** [comment]
请求支持.Net Core

**Comment by danielxiaoran** [comment]
可以加一下 钉钉群：11789671，具体交流下需求。

**Comment by mirbeta** [comment]
等待官方合并pr。。。

**Comment by ianpowell2017** [comment]
Hello, is this going to be merged in soon?  I am about to start on a project using Alibaba cloud and table storage.  I want to build this on an Linux ECS machine and we can't do this without .net core support.  Please can you decide whether this PR is to be approved or not?

**Comment by linys2333** [comment]
马上2020年了，仍旧未有.net core的包。。。伤心。

**Comment by acmajia** [comment]
+1，.net客户也是客户啊，希望尽早提供支持

**Comment by wanttobeamaster** [comment]
目前已经支持.Net Core了，欢迎大家体验并在社区反馈意见。
